### PR TITLE
added route to /members which shows all dg members and officers

### PR DESCRIPTION
**Pull request by itstehkman**
:^()

### CODE REVIEW

**Comment by itstehkman** [comment]
@chrisngobanh done! also, i pulled origin master to make sure my code was up to date. is htat ok?

**Comment by banhathome** [comment]
@itstehkman That's completely fine. I'll review your code right now

**Comment by banhathome** [comment]
Looks good to me! I approve

**Comment by chrisngobanh** [comment]
Hey Kareem, you keep pushing commits without fixing your code. How are you even testing your code to see if it works if you can't run the app.

**Comment by itstehkman** [comment]
@chrisngobanh i fucking suck man. sorry for my shitty commits

**Comment by banhathome** [comment]
Relax lol

**Comment by itstehkman** [comment]
@chrisngobanh done

**Comment by banhathome** [comment]
I approve of this PR. You may merge this PR after you update the branch

**Comment by itstehkman** [comment]
@chrisngobanh i just merged so be careful since you're working right now

**Pull request merged**
